[package]
name = "breakpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.7"
flate2 = "1.0.28"
glob = "0.3.1"
hmac-sha512 = "1.1.5"
json = "0.12.4"
reqwest = { version = "0.11.24", features = ["blocking"] }
tar = "0.4.40"
thiserror = "1.0.57"
url = "2.5.0"
